### ISSUE TITLE
[Improvement] Adding data product version on DATA_PRODUCT_ACTIVITY_COMPLETED notification event

### ISSUE THREAD

**Issue by gabrielefantini** [opendatamesh-initiative/odm-platform#194]
Adding the full data product descriptor inside the notification event of DATA_PRODUCT_ACTIVITY_COMPLETED.

**Comment by lattaai6** [comment]
Hello, I tried to fix the issue.

This is what I did:

Modified the ActivityService class to fetch the data product descriptor and include it in the notification event for DATA_PRODUCT_ACTIVITY_COMPLETED.

You can review changes in this commit: https://github.com/lattaai6/opendatamesh-initiative-odm-platform-194/commit/35163970ff0addc2b193951b4f82c54a0bbbe232.


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This issue was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
